### PR TITLE
Changes for Laravel 9

### PR DESCRIPTION
**Pull request by picklewagon**
This will get the package running with Laravel 9.

### CODE REVIEW

**Comment by spekulatius** [comment]
Hello @picklewagon,

looks good, I've merged it. Can you confirm if everything works before I tag a release?

Cheers,
Peter

**Comment by picklewagon** [comment]
> looks good, I've merged it. Can you confirm if everything works before I tag a release?

I can confirm that these changes work with laravel 9.

**Comment by spekulatius** [comment]
Awesome, thank you @picklewagon!

**Comment by spekulatius** [comment]
Done, 0.12.0 is released :+1:

**Pull request merged**
